# apply code review
name: apply-code-review

on:
  workflow_dispatch:
    inputs:
      REVIEW_DATA:
        description: ""
        required: true

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: MannLabs/alphashared/apply-code-review@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          REVIEW_DATA: ${{inputs.REVIEW_DATA}}
